version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: mims-db
    restart: always
    environment:
      POSTGRES_USER: mims_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: mims_geo_db
    ports:
      - "5432:5432"
    volumes:
      - mims_pg_data:/var/lib/postgresql/data

volumes:
  mims_pg_data: